// Generated by CoffeeScript 1.4.0

$(function() {
  var DependienteModel, DependienteView, Dependientes, DependientesView;
  DependienteModel = Backbone.Model.extend;
  DependienteView = Backbone.View.extend({
    tagName: 'li',
    render: function() {
      var html, template;
      template = Handlebars.compile(($("#dependienteCard")).html());
      html = template(this.model);
      this.$el.html(html);
      return this;
    }
  });
  Dependientes = Backbone.Collection.extend({
    model: DependienteModel,
    url: function() {
      return "http://localhost:8080/stele/usuario/dependientes";
    }
  });
  return DependientesView = Backbone.View.extend({
    tagName: 'ul',
    render: function() {
      this.collection.each(function(dependiente) {
        var dependienteView;
        dependienteView = new DependienteView({
          model: dependiente
        });
        return ($(this.el)).prepend(dependienteView.render().el);
      }, this);
      return this;
    }
  });
});
