recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6LdfQOcSAAAAAN8m4JJB2uIsYmyEWQQGbaCqxzt1"
    privateKey = "6LdfQOcSAAAAAFfVikBzCoW1X7wh1piAY0ymfxYG"

    // Include the noscript tags in the generated captcha
    includeNoScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

mailhide {
    publicKey = ""
    privateKey = ""
} 

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = false

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}